// this is an example top.hpp
// in reality it will be autogenerated by a python script

#include <Vserv_top.h>
#define TOP_TYPE Vserv_top
#define TOP_CLK clk

TOP_TYPE* top = nullptr;


static void set(const std::string& name, const std::string& num_str) {
	uint64_t value = std::stoll(num_str);
	if(false) {}
	else if(name == "i_rst") {
		top->i_rst = value;
	}
	else if(name == "i_ibus_rdt") {
		top->i_ibus_rdt = value;
	}
	else if(name == "i_timer_irq") {
		top->i_timer_irq = value;
	}
	else if(name == "i_dbus_rdt") {
		top->i_dbus_rdt = value;
	}
	else if(name == "decode.state") {
		assert(step0);
		top->serv_top__DOT__decode__DOT__state = value;
	}
	else {
		throw new std::runtime_error("Not an input or register: " + name);
	}
}
